channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - aiohttp=3.9.3
  - aiosignal=1.2.0
  - arrow-cpp=14.0.2
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - cryptography=42.0.5
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - dill=0.3.6
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - icu=73.1
  - intel-openmp=2023.1.0
  - joblib=1.2.0
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.5.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.44.2
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=8.0.1
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.14
  - ncurses=6.4
  - nettle=3.7.3
  - numexpr=2.8.7
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.1
  - orc=1.7.4
  - pandas=2.2.1
  - pip=23.3.1
  - psutil=5.9.0
  - pycparser=2.21
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.9
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - re2=2022.04.01
  - readline=8.2
  - responses=0.13.3
  - s2n=1.3.27
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.2.2
  - typing_extensions=4.9.0
  - tzdata=2024a
  - utf8proc=2.6.1
  - wheel=0.41.2
  - x264=1!157.20191217
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - accelerate==0.31.0
    - alembic==1.13.2
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.3.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.43.1
    - bleach==6.1.0
    - blis==0.7.11
    - catalogue==2.0.10
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - click==8.1.7
    - clip==1.0
    - cloudpathlib==0.18.1
    - coloredlogs==15.0.1
    - colorlog==6.8.2
    - comm==0.2.2
    - confection==0.1.5
    - conllu==4.5.3
    - contextlib2==21.6.0
    - contourpy==1.2.1
    - cupy-cuda114==10.6.0
    - cycler==0.12.1
    - cymem==2.0.8
    - datasets==2.20.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - deepspeed==0.14.2
    - defusedxml==0.7.1
    - diffusers==0.30.0
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - en-core-sci-scibert==0.5.4
    - en-core-sci-sm==0.5.4
    - en-core-web-sm==3.7.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - fastrlock==0.8.2
    - filelock==3.15.4
    - fonttools==4.51.0
    - fqdn==1.5.1
    - fsspec==2024.6.1
    - ftfy==6.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gloria==0.1
    - greenlet==3.0.3
    - h11==0.14.0
    - hi-ml-multimodal==0.2.2
    - hjson==3.1.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.2
    - humanfriendly==10.0
    - idna==3.8
    - imageio==2.34.0
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - invisible-watermark==0.2.0
    - ipykernel==6.29.4
    - ipython==8.18.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - json5==0.9.24
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.13.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.6
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.26.0
    - kiwisolver==1.4.5
    - langcodes==3.4.0
    - language-data==1.2.0
    - lazy-loader==0.4
    - lightning-utilities==0.11.2
    - mako==1.3.5
    - marisa-trie==1.2.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==3.0.2
    - ml-collections==0.1.1
    - murmurhash==1.0.10
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nltk==3.8.1
    - nmslib==2.1.1
    - notebook==7.1.2
    - notebook-shim==0.2.4
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu11==11.8.86
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - open-clip-torch==2.22.0
    - opencv-python==4.9.0.80
    - optuna==3.6.1
    - overrides==7.7.0
    - packaging==24.1
    - pandocfilters==1.5.1
    - parso==0.8.4
    - peft==0.10.1.dev0
    - pexpect==4.9.0
    - pillow==10.4.0
    - platformdirs==4.2.0
    - preshed==3.0.9
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - protobuf==3.20.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyarrow==17.0.0
    - pyarrow-hotfix==0.6
    - pybind11==2.6.1
    - pycocotools==2.0.7
    - pydantic==2.7.1
    - pydantic-core==2.18.2
    - pydicom==2.4.4
    - pygments==2.17.2
    - pynvml==11.5.0
    - pyparsing==3.1.4
    - pysbd==0.3.4
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytorch-lightning==2.2.1
    - pywavelets==1.6.0
    - pyyaml==6.0.2
    - pyzmq==25.1.2
    - referencing==0.34.0
    - regex==2024.7.24
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - rpds-py==0.18.0
    - safetensors==0.4.4
    - scikit-image==0.22.0
    - scikit-learn==1.5.1
    - scipy==1.13.1
    - scispacy==0.5.4
    - send2trash==1.8.3
    - sentencepiece==0.2.0
    - sentry-sdk==1.44.1
    - setproctitle==1.3.3
    - shellingham==1.5.4
    - simpleitk==2.4.0
    - smart-open==7.0.4
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - spacy==3.7.5
    - spacy-alignments==0.9.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - spacy-transformers==1.3.5
    - sqlalchemy==2.0.32
    - srsly==2.4.8
    - stack-data==0.6.3
    - sympy==1.13.2
    - terminado==0.18.1
    - thinc==8.2.4
    - threadpoolctl==3.5.0
    - tifffile==2024.2.12
    - timm==1.0.9
    - tinycss2==1.2.1
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torch==2.3.0+cu118
    - torchmetrics==1.3.2
    - torchvision==0.18.0+cu118
    - torchxrayvision==1.2.2
    - tornado==6.4
    - tqdm==4.66.5
    - traitlets==5.14.2
    - transformers==4.42.0.dev0
    - triton==2.3.0
    - typer==0.12.3
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.12.2
    - uri-template==1.3.0
    - urllib3==2.2.2
    - wandb==0.16.6
    - wasabi==1.1.3
    - wcwidth==0.2.13
    - weasel==0.4.1
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - wrapt==1.16.0
    - xformers==0.0.26.post1+cu118
    - zipp==3.18.1
